-- Baseline schema (generated from JPA entities, PostgreSQL dialect).
-- Existing databases are baselined at version 1 and skip this script.
create table api_keys (rate_limit_per_minute integer not null, approved_at bigint, created_at bigint not null, last_used_at bigint, total_calls bigint not null, id uuid not null, user_id uuid not null, key_prefix varchar(20), status varchar(20) not null check (status in ('PENDING','APPROVED','REJECTED','REVOKED')), expected_monthly_clicks varchar(50), key_hash varchar(64), app_name varchar(100) not null, raw_key varchar(100), ip_whitelist varchar(1000), purpose varchar(1000) not null, rejection_reason varchar(1000), website_url varchar(2048), primary key (id));
create table bio_link_items (active boolean not null, highlighted boolean not null, sort_order integer not null, click_count bigint not null, bio_page_id uuid, id uuid not null, icon varchar(50), title varchar(150) not null, url varchar(2048) not null, primary key (id));
create table bio_pages (verified boolean not null, created_at bigint not null, updated_at bigint not null, view_count bigint not null, id uuid not null, user_id uuid, theme varchar(50) not null, username varchar(50) not null unique, display_name varchar(100), bio_description varchar(1000), avatar_url varchar(2048), social_links varchar(2048), primary key (id));
create table click_analytics (bot boolean not null, clicked_at bigint not null, id uuid not null, variant_id uuid, short_code varchar(20) not null, bot_category varchar(100), utm_campaign varchar(100), utm_content varchar(100), utm_medium varchar(100), utm_source varchar(100), utm_term varchar(100), variant_label varchar(100), city varchar(255), country varchar(255), country_code varchar(255), ip_address varchar(255), referrer varchar(255), user_agent varchar(255), primary key (id));
create table url_mappings (ab_testing_enabled boolean not null, active boolean not null, health_status_code integer, preview_enabled boolean not null, click_count bigint not null, created_at bigint not null, expires_at bigint, health_response_time_ms bigint, last_health_check bigint, max_clicks bigint, id uuid not null, user_id uuid, workspace_id uuid, short_code varchar(20) not null unique, health_status varchar(30), health_error_message varchar(500), blocked_countries varchar(1000), blocked_ips varchar(2000), android_url varchar(2048), desktop_url varchar(2048), fallback_url varchar(2048), ios_url varchar(2048), original_url varchar(2048) not null, webhook_url varchar(2048), password_hash varchar(255), webhook_secret varchar(255), primary key (id));
create table url_variants (active boolean not null, weight_percent integer not null, click_count bigint not null, created_at bigint not null, id uuid not null, url_mapping_id uuid not null, label varchar(100) not null, target_url varchar(2048) not null, primary key (id));
create table users (two_factor_enabled boolean not null, created_at bigint not null, id uuid not null, role varchar(20) not null, username varchar(50) not null unique, two_factor_secret varchar(64), email varchar(100) not null unique, password varchar(255) not null, primary key (id));
create table workspace_members (joined_at bigint not null, id uuid not null, user_id uuid not null, workspace_id uuid not null, role varchar(20) not null check (role in ('ADMIN','MEMBER','VIEWER')), primary key (id), constraint uk_workspace_user unique (workspace_id, user_id));
create table workspace_permission_policies (can_create_link boolean not null, can_customize_qr boolean not null, can_delete_link boolean not null, can_export_reports boolean not null, can_manage_webhooks boolean not null, can_view_analytics boolean not null, updated_at bigint not null, id uuid not null, workspace_id uuid not null, role varchar(20) not null check (role in ('ADMIN','MEMBER','VIEWER')), primary key (id), constraint uk_ws_policy_role unique (workspace_id, role));
create table workspaces (created_at bigint not null, id uuid not null, owner_id uuid not null, name varchar(100) not null, slug varchar(120) not null unique, description varchar(500), primary key (id));
create index idx_apikey_hash on api_keys (key_hash);
create index idx_apikey_user on api_keys (user_id);
create index idx_apikey_status on api_keys (status);
create index idx_biolink_page on bio_link_items (bio_page_id);
create index idx_biolink_order on bio_link_items (sort_order);
create index idx_biopage_user on bio_pages (user_id);
create index idx_analytics_short_code on click_analytics (short_code);
create index idx_short_code on url_mappings (short_code);
create index idx_variant_mapping on url_variants (url_mapping_id);
create index idx_username on users (username);
create index idx_email on users (email);
create index idx_wm_workspace on workspace_members (workspace_id);
create index idx_wm_user on workspace_members (user_id);
create index idx_wpp_workspace on workspace_permission_policies (workspace_id);
create index idx_wpp_role on workspace_permission_policies (role);
create index idx_workspace_slug on workspaces (slug);
create index idx_workspace_owner on workspaces (owner_id);
alter table if exists api_keys add constraint FK89d4ddye91twgmx31epv7ro7h foreign key (user_id) references users;
alter table if exists bio_link_items add constraint FK1f06o78n7iopucyxqqmatbge8 foreign key (bio_page_id) references bio_pages;
alter table if exists bio_pages add constraint FKrtqcyfor7f4e9yh0jcdb20tnn foreign key (user_id) references users;
alter table if exists url_mappings add constraint FKpvq6ci6x5jvjoea6eih0fp0o3 foreign key (user_id) references users;
alter table if exists url_mappings add constraint FK2a6w71gaqcpdslb3m7fvwualw foreign key (workspace_id) references workspaces;
alter table if exists url_variants add constraint FKfbbkuterijebo8setnmjnejg9 foreign key (url_mapping_id) references url_mappings;
alter table if exists workspace_members add constraint FK6vtnpc3eexk504u61uepn40p1 foreign key (user_id) references users;
alter table if exists workspace_members add constraint FKw9hq87n3rvq2c4j47qo78i5r foreign key (workspace_id) references workspaces;
alter table if exists workspace_permission_policies add constraint FKsjjw7b5tgb54xdvi6oexox0t6 foreign key (workspace_id) references workspaces;
alter table if exists workspaces add constraint FK58ks96jjlsbhsh21cen7hr59h foreign key (owner_id) references users;
